#设置这个微服务的security的相关信息在访问auth-service(认证服务器)的时候需要用到
#这个微服务是客户端模式
security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
#为什么我们要进行服务注册但是却不指定eureka.client.service-url.defaultZone这个属性呢?
#因为registry微服务(eureka server)使用的是默认的地址和端口即(http://localhost:8761)
#故我们不需要在其他运行在本机的微服务中特指

spring:
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /accounts
  port: 6000

#开启熔断服务
feign:
  hystrix:
    enabled: true